### ISSUE TITLE
OverflowError: string longer than 2147483647 bytes

### ISSUE THREAD

**Issue by BioGeek** [jina-ai/jina-hubble-sdk#170]
I get an `OverflowError: string longer than 2147483647 bytes` when I run `lc-serve deploy babyagi `:

```
$ lc-serve deploy babyagi    
⠇ Pushing `/tmp/tmpqonzhjbz` ...🔐 You are logged in to Jina AI as BioGeek (username: BioGeek). To log out, use jina auth logout.
Please report this session_id: [yellow bold]5d27a10c-e609-11ed-90b1-0b09b5b0a9c3[/] to https://github.com/jina-ai/jina-hubble-sdk/issues
Traceback (most recent call last):
  File "/home/j.vangoey/.pyenv/versions/chat-py39/bin/lc-serve", line 8, in <module>
    sys.exit(serve())
  File "/home/j.vangoey/.pyenv/versions/3.9.13/envs/chat-py39/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/j.vangoey/.pyenv/versions/3.9.13/envs/chat-py39/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/j.vangoey/.pyenv/versions/3.9.13/envs/chat-py39/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/j.vangoey/.pyenv/versions/3.9.13/envs/chat-py39/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/j.vangoey/.pyenv/versions/3.9.13/envs/chat-py39/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/j.vangoey/.pyenv/versions/3.9.13/envs/chat-py39/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/j.vangoey/.pyenv/versions/3.9.13/envs/chat-py39/lib/python3.9/site-packages/lcserve/flow.py", line 33, in wrapper
    return asyncio.run(f(*args, **kwargs))
  File "/home/j.vangoey/.pyenv/versions/3.9.13/envs/chat-py39/lib/python3.9/site-packages/nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
  File "/home/j.vangoey/.pyenv/versions/3.9.13/envs/chat-py39/lib/python3.9/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "/home/j.vangoey/.pyenv/versions/3.9.13/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/home/j.vangoey/.pyenv/versions/3.9.13/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/home/j.vangoey/.pyenv/versions/3.9.13/envs/chat-py39/lib/python3.9/site-packages/lcserve/__main__.py", line 254, in babyagi
    await serve_babyagi_on_jcloud(
  File "/home/j.vangoey/.pyenv/versions/3.9.13/envs/chat-py39/lib/python3.9/site-packages/lcserve/__main__.py", line 81, in serve_babyagi_on_jcloud
    await serve_on_jcloud(
  File "/home/j.vangoey/.pyenv/versions/3.9.13/envs/chat-py39/lib/python3.9/site-packages/lcserve/__main__.py", line 47, in serve_on_jcloud
    gateway_id_wo_tag, is_websocket = push_app_to_hubble(
  File "/home/j.vangoey/.pyenv/versions/3.9.13/envs/chat-py39/lib/python3.9/site-packages/lcserve/flow.py", line 284, in push_app_to_hubble
    return HubIO(args).push().get('id'), _any_websocket_router(app)
  File "/home/j.vangoey/.pyenv/versions/3.9.13/envs/chat-py39/lib/python3.9/site-packages/hubble/__init__.py", line 48, in arg_wrapper
    return func(*args, **kwargs)
  File "/home/j.vangoey/.pyenv/versions/3.9.13/envs/chat-py39/lib/python3.9/site-packages/hubble/executor/hubio.py", line 597, in push
    raise e
  File "/home/j.vangoey/.pyenv/versions/3.9.13/envs/chat-py39/lib/python3.9/site-packages/hubble/executor/hubio.py", line 580, in push
    image = self._send_push_request(
  File "/home/j.vangoey/.pyenv/versions/3.9.13/envs/chat-py39/lib/python3.9/site-packages/hubble/executor/hubio.py", line 358, in _send_push_request
    resp = upload_file(
  File "/home/j.vangoey/.pyenv/versions/3.9.13/envs/chat-py39/lib/python3.9/site-packages/hubble/executor/helper.py", line 523, in upload_file
    response = getattr(requests, method)(url, data=data, headers=headers, stream=stream)
  File "/home/j.vangoey/.pyenv/versions/3.9.13/envs/chat-py39/lib/python3.9/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/home/j.vangoey/.pyenv/versions/3.9.13/envs/chat-py39/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/j.vangoey/.pyenv/versions/3.9.13/envs/chat-py39/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/j.vangoey/.pyenv/versions/3.9.13/envs/chat-py39/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/j.vangoey/.pyenv/versions/3.9.13/envs/chat-py39/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/j.vangoey/.pyenv/versions/3.9.13/envs/chat-py39/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/j.vangoey/.pyenv/versions/3.9.13/envs/chat-py39/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/j.vangoey/.pyenv/versions/3.9.13/envs/chat-py39/lib/python3.9/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/home/j.vangoey/.pyenv/versions/3.9.13/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/j.vangoey/.pyenv/versions/3.9.13/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/j.vangoey/.pyenv/versions/3.9.13/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/j.vangoey/.pyenv/versions/3.9.13/lib/python3.9/http/client.py", line 1079, in _send_output
    self.send(chunk)
  File "/home/j.vangoey/.pyenv/versions/3.9.13/lib/python3.9/http/client.py", line 1001, in send
    self.sock.sendall(data)
  File "/home/j.vangoey/.pyenv/versions/3.9.13/lib/python3.9/ssl.py", line 1205, in sendall
    v = self.send(byte_view[count:])
  File "/home/j.vangoey/.pyenv/versions/3.9.13/lib/python3.9/ssl.py", line 1174, in send
    return self._sslobj.write(data)
OverflowError: string longer than 2147483647 bytes
```

**Comment by Andrei997** [comment]
Hi @BioGeek , I've tried this and was not able to reproduce, could you try again and tell me if you're still experiencing this problem ?
