### ISSUE TITLE
[yellow bold]775bf278-f52d-11ed-86fe-00155dd1a7dd[/]

### ISSUE THREAD

**Issue by lausiv7** [jina-ai/jina-hubble-sdk#174]
plz check below, thanks

🔐 Successfully logged in to Jina AI as lausiv (username: BIGZAM)!
⠦ Pushing `/tmp/tmpl3c4wyan` ...🔐 You are logged in to Jina AI as lausiv (username: BIGZAM). To log out, use jina auth logout.
Please report this session_id: [yellow bold]775bf278-f52d-11ed-86fe-00155dd1a7dd[/] to
https://github.com/jina-ai/jina-hubble-sdk/issues
Traceback (most recent call last):
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/hubble/__init__.py", line 47, in arg_wrapper
    Client(jsonify=True).get_user_info()
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/hubble/client/client.py", line 84, in get_user_info
    resp = self.handle_request(
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/hubble/client/base.py", line 106, in handle_request
    raise e
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/hubble/client/base.py", line 96, in handle_request
    self._handle_error_request(resp)
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/hubble/client/base.py", line 53, in _handle_error_request
    raise ExceptionCls(response=resp, data=data, message=message, code=code)
hubble.excepts.AuthenticationRequiredError: 40103: AuthenticationRequiredWithBearerChallengeError: Token invalid or expired.

During handling of the above exception, another exception occurred:

**Comment by mapleeit** [comment]
Thanks for report. The log says that your token is invalid or expired. Could you check that and maybe recreat one? @lausiv7
