### ISSUE TITLE
bug: pushing deleted executor again fails

### ISSUE THREAD

**Issue by fogx** [jina-ai/jina-hubble-sdk#94]
I created an Executor and pushed it to the hub, then deleted it in the UI and tried to push it again from the code.

I get the following error
> ❯ jina hub push ./executors/MyExecutor48
⠧ Pushing `./executors/MyExecutor48` ...🔐 You are logged in to Jina AI as leon.wolf. To log out, use jina auth logout.
⠙ Uploading...ERROR  HubIO@6359 Please report this session_id: [yellow bold]308bde38-545d-11ed-bf72-00155d1458da[/] to https://github.com/jina-ai/jina/issues               [10/25/22 14:04:36]
Traceback (most recent call last):                                                                                                                                               
  File "/home/user/sandbox/.venv/bin/jina", line 8, in <module>
    sys.exit(main())
  File "/home/user/sandbox/.venv/lib/python3.9/site-packages/jina_cli/__init__.py", line 143, in main
    getattr(api, args.cli.replace('-', '_'))(args)
  File "/home/user/sandbox/.venv/lib/python3.9/site-packages/jina_cli/api.py", line 186, in hub
    getattr(HubIO(args), args.hub)()
  File "/home/user/sandbox/.venv/lib/python3.9/site-packages/jina/hubble/hubio.py", line 550, in push
    raise e
  File "/home/user/sandbox/.venv/lib/python3.9/site-packages/jina/hubble/hubio.py", line 508, in push
    raise Exception(
Exception: RequestedEntityNotFoundError: Executor(2ecno8cm) was not found in the system. session_id: 308bde38-545d-11ed-bf72-00155d1458da

**Comment by floralatin** [comment]
I write a docs about: [Multi-terminal data synchronization problem](https://docs.google.com/document/d/10cNplEIoPAk1masgyuqzrQeXQp8RQa-ybDOnsNFugCw/edit#)

**Comment by nomagick** [comment]
Maybe solved by https://github.com/jina-ai/jina-hubble-sdk/issues/125

**Comment by delgermurun** [comment]
Solved by #137
